public class InventoryTriggerHandler {
    public static void createInventoryHistory(List<InventoryHistory__c> ihList){
        List<InventoryHistory__c> ihiList = new List<InventoryHistory__c>();
        /*
        for(Account acc : trigger.new){
            Contact con = new Contact();
            con.LastName = acc.Name;
            con.AccountId = acc.Id;
            conList.add(con);
        }
        if(conList !=null){
             insert conList;
        }
    */
        update ihilist;
        }
    
}